SKILLS = [
    "python",
    "java",
    "sql",
    "react",
    "flask",
    "django",
    "spring boot",
    "rest api",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "git",
    "javascript",
    "typescript",
    "node.js",
    "c++",
    "c#",
    "machine learning",
    "nlp",
    "pandas",
    "numpy",
    "power bi",
    "tableau",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "elasticsearch",
    "graphql",
    "microservices",
    "ci cd",
    "jenkins",
    "gitlab",
    "github",
    "terraform",
    "ansible",
    "gcp",
    "ec2",
    "s3",
    "lambda",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "keras",
    "opencv",
    "spark",
    "hadoop",
    "kafka",
    "airflow",
    "linux",
    "bash",
    "css",
    "html",
    "sass",
    "webpack",
    "vue.js",
    "angular",
    "next.js",
    "express",
    "fastapi",
    "go",
    "rust",
    "ruby",
    "php",
    "scala",
    "kotlin",
    "swift",
    "ios",
    "android",
    "react native",
    "flutter",
    "junit",
    "pytest",
    "selenium",
    "jira",
    "scrum",
    "spring",
    "hibernate",
    "oauth",
    "jwt",
    "security",
    "blockchain",
    "web3",
    "solidity",
    "etl",
    "data warehouse",
    "big data",
    "analytics",
    "business intelligence",
    "salesforce",
    "oracle",
    "nosql",
]


ROLE_PROFILES = {
    "backend_engineer": {
        "keywords": ["backend", "server", "api", "infrastructure"],
        "weights": {
            "python": 1.0,
            "java": 0.95,
            "c++": 0.85,
            "go": 0.9,
            "node.js": 0.8,
            "spring boot": 1.0,
            "django": 0.9,
            "flask": 0.85,
            "rest api": 1.0,
            "graphql": 0.8,
            "docker": 0.9,
            "kubernetes": 0.85,
            "ci cd": 0.8,
            "microservices": 0.9,
            "aws": 0.85,
            "azure": 0.8,
            "gcp": 0.75,
        },
    },
    "frontend_engineer": {
        "keywords": ["frontend", "ui", "ux", "client"],
        "weights": {
            "javascript": 1.0,
            "typescript": 0.95,
            "react": 1.0,
            "angular": 0.9,
            "vue.js": 0.9,
            "next.js": 0.85,
            "html": 0.95,
            "css": 0.95,
            "rest api": 0.75,
            "graphql": 0.7,
        },
    },
    "data_scientist": {
        "keywords": ["data", "ml", "analytics", "statistics"],
        "weights": {
            "python": 1.0,
            "sql": 0.95,
            "machine learning": 1.0,
            "tensorflow": 0.95,
            "pytorch": 0.95,
            "scikit-learn": 0.9,
            "pandas": 0.95,
            "numpy": 0.95,
            "spark": 0.85,
        },
    },
    "devops_engineer": {
        "keywords": ["devops", "infrastructure", "deployment", "automation"],
        "weights": {
            "docker": 1.0,
            "kubernetes": 1.0,
            "aws": 1.0,
            "azure": 0.95,
            "gcp": 0.9,
            "terraform": 0.95,
            "ansible": 0.9,
            "jenkins": 0.9,
            "ci cd": 1.0,
            "linux": 0.95,
            "bash": 0.9,
        },
    },
    "full_stack_engineer": {
        "keywords": ["full stack", "fullstack", "end-to-end"],
        "weights": {
            "javascript": 1.0,
            "python": 0.95,
            "typescript": 0.9,
            "react": 0.95,
            "node.js": 0.95,
            "express": 0.9,
            "sql": 0.95,
            "mongodb": 0.85,
            "rest api": 0.95,
        },
    },
}


CERTIFICATIONS = [
    "aws certified solutions architect",
    "aws certified developer",
    "aws certified devops",
    "azure fundamentals",
    "azure solutions architect",
    "google cloud professional",
    "kubernetes certified application developer",
    "certified kubernetes administrator",
    "terraform associate",
    "pmp",
    "scrum master",
    "certified scrum master",
]


LANGUAGES = [
    "english",
    "spanish",
    "french",
    "german",
    "italian",
    "portuguese",
    "russian",
    "chinese",
    "japanese",
    "korean",
]
